import { z } from "zod";
import { asBoolean } from "./lib/json.js";

const envSchema = z.object({
  PORT: z.string().default("8080"),
  TRUST_PROXY_HOPS: z.string().default("1"),
  RATE_WINDOW_MS: z.string().default("60000"),
  RATE_MAX: z.string().default("120"),
  REQUEST_TIMEOUT_MS: z.string().default("15000"),
  AUTH_REQUIRED: z.string().default("true"),
  EXECUTOR_MODE: z.enum(["dry_run", "provider"]).default("dry_run"),
  PLATFORM_NOTIFICATION_SERVICE_URL: z.string().default("http://platform-notification-service.directus.svc.cluster.local:8080"),
  BROWSER_PUSH_VAPID_SUBJECT: z.string().default(""),
  BROWSER_PUSH_VAPID_PUBLIC_KEY: z.string().default(""),
  BROWSER_PUSH_VAPID_PRIVATE_KEY: z.string().default(""),
  BROWSER_PUSH_VAPID_VAULT_PATH: z.string().default("secret/data/platform-notification/browser-push/vapid"),
  BROWSER_PUSH_VAPID_PUBLIC_KEY_VAULT_KEY: z.string().default("public_key"),
  BROWSER_PUSH_VAPID_PRIVATE_KEY_VAULT_KEY: z.string().default("private_key"),
  BROWSER_PUSH_VAPID_SUBJECT_VAULT_KEY: z.string().default("subject"),
  EMAIL_SMTP_HOST: z.string().default(""),
  EMAIL_SMTP_PORT: z.string().default(""),
  EMAIL_SMTP_SECURE: z.string().default(""),
  EMAIL_SMTP_USERNAME: z.string().default(""),
  EMAIL_SMTP_PASSWORD: z.string().default(""),
  EMAIL_FROM: z.string().default(""),
  EMAIL_REPLY_TO: z.string().default(""),
  EMAIL_SMTP_VAULT_PATH: z.string().default("secret/data/cloudflare-smtp-secret"),
  EMAIL_SMTP_HOST_VAULT_KEY: z.string().default("host"),
  EMAIL_SMTP_PORT_VAULT_KEY: z.string().default("port"),
  EMAIL_SMTP_SECURE_VAULT_KEY: z.string().default("secure"),
  EMAIL_SMTP_USERNAME_VAULT_KEY: z.string().default("username"),
  EMAIL_SMTP_PASSWORD_VAULT_KEY: z.string().default("value"),
  EMAIL_FROM_VAULT_KEY: z.string().default("from"),
  EMAIL_REPLY_TO_VAULT_KEY: z.string().default("reply_to"),
  INTERNAL_TOKEN: z.string().default(""),
  INTERNAL_TOKEN_VAULT_PATH: z.string().default("secret/data/platform-notification-service"),
  INTERNAL_TOKEN_VAULT_KEY: z.string().default("token"),
  VAULT_ADDR: z.string().default("http://vault.vault.svc.cluster.local:8200"),
  VAULT_TOKEN_FILE: z.string().default("/vault-secrets/vault-token"),
  TOKEN_CACHE_SECONDS: z.string().default("300"),
  OPENAPI_SERVER_URL: z.string().default("http://platform-notification-executor.directus.svc.cluster.local:8080")
});

const parsed = envSchema.parse(process.env);

export const config = {
  port: Math.max(1, Math.min(65535, Number(parsed.PORT) || 8080)),
  trustProxyHops: Math.max(0, Number(parsed.TRUST_PROXY_HOPS) || 1),
  rateWindowMs: Math.max(1000, Number(parsed.RATE_WINDOW_MS) || 60_000),
  rateMax: Math.max(1, Number(parsed.RATE_MAX) || 120),
  requestTimeoutMs: Math.max(1000, Number(parsed.REQUEST_TIMEOUT_MS) || 15_000),
  authRequired: asBoolean(parsed.AUTH_REQUIRED, true),
  executorMode: parsed.EXECUTOR_MODE,
  platformNotificationServiceUrl: parsed.PLATFORM_NOTIFICATION_SERVICE_URL.replace(/\/+$/, ""),
  browserPushVapidSubject: parsed.BROWSER_PUSH_VAPID_SUBJECT,
  browserPushVapidPublicKey: parsed.BROWSER_PUSH_VAPID_PUBLIC_KEY,
  browserPushVapidPrivateKey: parsed.BROWSER_PUSH_VAPID_PRIVATE_KEY,
  browserPushVapidVaultPath: parsed.BROWSER_PUSH_VAPID_VAULT_PATH,
  browserPushVapidPublicKeyVaultKey: parsed.BROWSER_PUSH_VAPID_PUBLIC_KEY_VAULT_KEY,
  browserPushVapidPrivateKeyVaultKey: parsed.BROWSER_PUSH_VAPID_PRIVATE_KEY_VAULT_KEY,
  browserPushVapidSubjectVaultKey: parsed.BROWSER_PUSH_VAPID_SUBJECT_VAULT_KEY,
  emailSmtpHost: parsed.EMAIL_SMTP_HOST,
  emailSmtpPortRaw: parsed.EMAIL_SMTP_PORT,
  emailSmtpPort: Math.max(1, Math.min(65535, Number(parsed.EMAIL_SMTP_PORT) || 587)),
  emailSmtpSecureRaw: parsed.EMAIL_SMTP_SECURE,
  emailSmtpSecure: asBoolean(parsed.EMAIL_SMTP_SECURE, false),
  emailSmtpUsername: parsed.EMAIL_SMTP_USERNAME,
  emailSmtpPassword: parsed.EMAIL_SMTP_PASSWORD,
  emailFrom: parsed.EMAIL_FROM,
  emailReplyTo: parsed.EMAIL_REPLY_TO,
  emailSmtpVaultPath: parsed.EMAIL_SMTP_VAULT_PATH,
  emailSmtpHostVaultKey: parsed.EMAIL_SMTP_HOST_VAULT_KEY,
  emailSmtpPortVaultKey: parsed.EMAIL_SMTP_PORT_VAULT_KEY,
  emailSmtpSecureVaultKey: parsed.EMAIL_SMTP_SECURE_VAULT_KEY,
  emailSmtpUsernameVaultKey: parsed.EMAIL_SMTP_USERNAME_VAULT_KEY,
  emailSmtpPasswordVaultKey: parsed.EMAIL_SMTP_PASSWORD_VAULT_KEY,
  emailFromVaultKey: parsed.EMAIL_FROM_VAULT_KEY,
  emailReplyToVaultKey: parsed.EMAIL_REPLY_TO_VAULT_KEY,
  internalToken: parsed.INTERNAL_TOKEN,
  internalTokenVaultPath: parsed.INTERNAL_TOKEN_VAULT_PATH,
  internalTokenVaultKey: parsed.INTERNAL_TOKEN_VAULT_KEY,
  vaultAddr: parsed.VAULT_ADDR.replace(/\/+$/, ""),
  vaultTokenFile: parsed.VAULT_TOKEN_FILE,
  tokenCacheSeconds: Math.max(5, Number(parsed.TOKEN_CACHE_SECONDS) || 300),
  openApiServerUrl: parsed.OPENAPI_SERVER_URL
};
